# Generated by Django 6.0.7 on 2026-09-28 05:20

import django.core.validators
import django.db.models.deletion
import restaurant.models
import restaurant.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
                ('slug', models.SlugField(help_text='Unique category identifier; suggested from the name.', max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Optional category photo. JPEG, PNG or WebP, up to 5 MB and 20 megapixels.', upload_to=restaurant.models.category_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), restaurant.validators.validate_menu_image])),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the menu.')),
                ('is_active', models.BooleanField(default=True, help_text='Hide this category and all its dishes by clearing this box.', verbose_name='Show category on menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu category',
                'verbose_name_plural': 'Menu categories',
                'ordering': ['display_order', 'name', 'pk'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='menu_category_public_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Dish name')),
                ('slug', models.SlugField(help_text='Unique dish identifier; suggested from the name.', max_length=180, unique=True)),
                ('image', models.ImageField(help_text='Dish photo. JPEG, PNG or WebP, up to 5 MB and 20 megapixels.', upload_to=restaurant.models.item_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), restaurant.validators.validate_menu_image])),
                ('description', models.TextField(help_text='Ingredients and flavours shown on the menu.')),
                ('badge_label', models.CharField(blank=True, help_text='Optional dish label, such as Most loved.', max_length=40)),
                ('mrp_price', models.DecimalField(decimal_places=2, help_text='Regular price in dollars; must be greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='MRP')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price, greater than zero and lower than MRP.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Discount price')),
                ('is_available', models.BooleanField(default=True, help_text='Unavailable dishes remain visible without an order link.', verbose_name='Available to order')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Move or remove dishes before deleting their category.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurant.menucategory')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ['display_order', 'name', 'pk'],
                'indexes': [models.Index(fields=['category', 'display_order'], name='menu_item_category_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mrp_price__gt', 0)), name='menu_item_positive_mrp'), models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), models.Q(('discount_price__gt', 0), ('discount_price__lt', models.F('mrp_price'))), _connector='OR'), name='menu_item_valid_discount')],
            },
        ),
    ]
