# Generated by Django 6.0.7 on 2026-09-28 09:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_seed_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, help_text='Regular price in CAD; must be greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='MRP'),
        ),
    ]
