# Generated by Django 6.0.7 on 2026-09-28 10:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_align_price_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='layout',
            field=models.CharField(choices=[('cards', 'Cards'), ('compact', 'Compact rows')], default='cards', help_text='Use compact rows for sides, drinks or other small products.', max_length=10),
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Size or option, for example S, M or L.', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='restaurant.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('item', 'label'), name='menu_variant_unique_label'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='menu_variant_positive_price'), models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), models.Q(('discount_price__gt', 0), ('discount_price__lt', models.F('price'))), _connector='OR'), name='menu_variant_valid_discount')],
            },
        ),
    ]
